### ISSUE TITLE
erlang_js doesn't build on darwin11

### ISSUE THREAD

**Issue by krestenkrab** [basho/erlang_js#26]
My machine reports this:

```
Darwin dhcp-218.dyn81-121.trifork.com 11.4.0 
Darwin Kernel Version 11.4.0: Mon Apr  9 19:32:15 PDT 2012; 
root:xnu 1699.26.8~1/RELEASE_X86_64 x86_64
```

During configure, I get

```
checking host system type... i386-apple-darwin11.4.0
```

Which is not a platform being matched in current `rebar.config`

Compiling fails with some header file isses.

I tried to upgrade to nspr-4.9.1 (erlang_js is currently using 4.8), and it seems to compile just fine.

**Comment by dizzyd** [comment]
Hi Kresten,

A fresh checkout of erlang_js builds ok for me on the same platform,
with Erlang R14B04/R15B01 What version of gcc are you using?

My uname -a:

Darwin luna.dizzynet 11.4.0 Darwin Kernel Version 11.4.0: Mon Apr  9
19:32:15 PDT 2012; root:xnu-1699.26.8~1/RELEASE_X86_64 x86_64

My gcc -v:

Using built-in specs.
Target: i686-apple-darwin11
Configured with:
/private/var/tmp/llvmgcc42/llvmgcc42-2336.9~22/src/configure
--disable-checking --enable-werror
--prefix=/Applications/Xcode.app/Contents/Developer/usr/llvm-gcc-4.2
--mandir=/share/man --enable-languages=c,objc,c++,obj-c++
--program-prefix=llvm-
--program-transform-name=/^[cg][^.-]*$/s/$/-4.2/
--with-slibdir=/usr/lib --build=i686-apple-darwin11
--enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2336.9~22/dst-llvmCore/Developer/usr/local
--program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11
--target=i686-apple-darwin11
--with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)

**Comment by krestenkrab** [comment]
Hmm, my gcc says [see below] slightly older version than yours it seems ... 

krab$ gcc -v
Using built-in specs.
Target: i686-apple-darwin11
Configured with: /private/var/tmp/llvmgcc42/llvmgcc42-2335.15~25/src/configure --disable-checking --enable-werror --prefix=/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]*$/s/$/-4.2/ --with-slibdir=/usr/lib --build=i686-apple-darwin11 --enable-llvm=/private/var/tmp/llvmgcc42/llvmgcc42-2335.15~25/dst-llvmCore/Developer/usr/local --program-prefix=i686-apple-darwin11- --host=x86_64-apple-darwin11 --target=i686-apple-darwin11 --with-gxx-include-dir=/usr/include/c++/4.2.1
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)

**Comment by lfeng** [comment]
So... How to fix it?

**Comment by dizzyd** [comment]
Random idea that occurred to me -- are you using the rebar that's part of the erlang_js distribution or a different version?

**Comment by cmeiklejohn** [comment]
I've updated the rebar that's distributed with erlang_js to now honor the platform specific strings and apply the correct build flags.  I'm going to close this for now, as I imagine most of us no longer have the platform to confirm the fix, but feel free to reopen if this is still an issue.
