### ISSUE TITLE
Xcode 4.4 and Mountain Lion

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/erlang_js#28]
erlang_js will not build on Xcode 4.4 with Mountain Lion. 

Couple things I'm noticing with nsprpub:
- The header files are no longer in the location assumed by the Makefile, even after symlinking /Developer to /Applications/Xcode.app/Contents/Developer.
- The header files appear only present in the MacOSX10.7.sdk (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk/Developer/Headers/FlatCarbon) and are not present in the MacOSX10.8.sdk at all.  I'm assuming the 10.7.sdk is only present if you've specifically installed it through the developer portal or have upgraded Lion (with Xcode) to Mountain Lion.

**Comment by lfeng** [comment]
Me too, it can't build on Xcode 4.4 with Mountain Lion.

**Comment by neuhausler** [comment]
Try to rebuild Erlang as a 64 bit app on Mountain Lion, that seems to have fixed the problem for me.

**Comment by woo37830** [comment]
Trying to convert an old NeXTStep gui program to Cocoa.  I've put files into XCode on Mountain Lion.
My code had

 #import <appkit/Application.h>

and things like

```
if ([NXApp loadNibSection:"Stereo.nib" owner:NXApp withNames:NO])
    [NXApp run];

[NXApp free];
```

and

```
    [inputText setDelegate:self];
    [[NXApp appListener] setServicesDelegate:self];
```

Any hints on where I would find their "equivalents"?  Where are the headers and standard libraries on Mountain Lion?

**Comment by seancribbs** [comment]
@woo37830 I think you have the wrong repository, sir.

**Comment by cmeiklejohn** [comment]
Closing basho/erlang_js#28, as basho/riak#364 is tracking.  I've confirmed that this build _does not_ fail when building erlang_js outside of the Riak respository.
