### ISSUE TITLE
Compilation issues with OTP 18.3: "Failed to load erlang_js_drv.so"

### ISSUE THREAD

**Issue by rhumbertgz** [basho/erlang_js#61]
Hello, I have been trying to compile erlang_js with OTP 18.3, but allways I get this message  "Failed to load erlang_js_drv.so". I tried in Ubunto 14.0.04 and OSX 10.11.4.

Here you can find the full log of my error: https://gist.github.com/rhumbertgz/ee0bf432edfa89ffa0a47405f3250fcd

Any suggestion?

Thanks in advance,
Humberto

**Comment by whitfin** [comment]
See https://github.com/basho/erlang_js/pull/58

**Comment by rhumbertgz** [comment]
Thanks @zackehh!

That fixed my problem, now it works in both Linux and OSX :)
